# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-04 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20160223_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='people',
            field=models.IntegerField(default=0),
        ),
    ]
