# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-04 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20200604_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
