# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-05 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_reservation_number_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='capacity_percent',
            field=models.IntegerField(default=0),
        ),
    ]
