# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-05 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20200605_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='total_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
