# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-05 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_restaurant_total_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='capacity_reserved',
            field=models.IntegerField(default=0),
        ),
    ]
