# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-27 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_reservebyhour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.AddField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='coming',
            field=models.DateTimeField(),
        ),
    ]
