# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-27 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_reservation_leaving'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
