# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-29 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20200628_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='capacity_reserved',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='capacity_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='total_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
