# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-27 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_reservation_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservebyhour',
            name='hour',
        ),
        migrations.AddField(
            model_name='reservebyhour',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
