# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-29 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20200628_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='duration',
        ),
    ]
