# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-01 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_remove_reservation_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='closed',
            new_name='closed_dinner',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='open',
            new_name='closed_lunch',
        ),
        migrations.AddField(
            model_name='reservebyhour',
            name='capacity_free',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_dinner',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_lunch',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
