# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-01 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_auto_20200630_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='closed_dinner',
            new_name='close_dinner',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='closed_lunch',
            new_name='close_lunch',
        ),
    ]
