# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-10 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_auto_20200701_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cellphone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='telephone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
